#!/usr/bin/env python3
"""PrimeSum test and benchmark harness.

The C programs are treated as black-box executables with one stable contract:

    <executable> <endpoint> --sum-only

The harness keeps correctness baselines separate from performance history:

    baseline/expected-sums.tsv
    baseline/program-runs.tsv
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import platform
import shutil
import statistics
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable


TEST_DIR = Path(__file__).resolve().parent
PRIME_DIR = TEST_DIR.parent
DEFAULT_BASELINE_DIR = TEST_DIR / "baseline"
DEFAULT_EXPECTED = DEFAULT_BASELINE_DIR / "expected-sums.tsv"
DEFAULT_RUNS = DEFAULT_BASELINE_DIR / "program-runs.tsv"


@dataclass(frozen=True)
class Endpoint:
    label: str
    end: int
    kind: str


@dataclass
class RunResult:
    ok: bool
    elapsed: float
    stdout: str
    returncode: int
    error: str = ""


@dataclass
class TimingStats:
    repeats: int
    best: float
    median: float
    mean: float
    stdev: float
    total: float


def parse_nonnegative_int(text: str) -> int:
    value = int(text)
    if value < 0:
        raise argparse.ArgumentTypeError("value must be nonnegative")
    return value


def parse_positive_float(text: str) -> float:
    value = float(text)
    if value <= 0:
        raise argparse.ArgumentTypeError("value must be positive")
    return value


def unique_endpoints(rows: Iterable[Endpoint]) -> list[Endpoint]:
    seen: set[int] = set()
    result: list[Endpoint] = []
    for row in rows:
        if row.end < 2 or row.end in seen:
            continue
        seen.add(row.end)
        result.append(row)
    return sorted(result, key=lambda item: item.end)


def standard_endpoints(max_exp: int) -> list[Endpoint]:
    rows: list[Endpoint] = []

    for n in [2, 3, 4, 5, 6, 7, 8, 9, 10, 31, 32, 33, 63, 64, 65, 97, 100, 101]:
        rows.append(Endpoint(f"small_{n}", n, "small"))

    for n in [999, 1000, 1001, 9999, 10000, 10001, 99999, 100000, 100001]:
        rows.append(Endpoint(f"decimal_{n}", n, "decimal"))

    for exp in range(1, max_exp + 1):
        base = 1 << exp
        rows.append(Endpoint(f"2^{exp}", base, "power"))
        rows.append(Endpoint(f"2^{exp}-1", base - 1, "power_edge"))
        rows.append(Endpoint(f"2^{exp}+1", base + 1, "power_edge"))

    for exp in range(10, max_exp + 1, 4):
        base = 1 << exp
        rows.append(Endpoint(f"3*2^{exp-1}", 3 * (base >> 1), "non_power"))
        rows.append(Endpoint(f"5*2^{exp-2}", 5 * (base >> 2), "non_power"))

    block_size = 1 << 19
    for segment in [1, 2, 4, 8, 16]:
        high = 2 * segment * block_size + 1
        rows.append(Endpoint(f"seg{segment}_end-1", high - 1, "segment_edge"))
        rows.append(Endpoint(f"seg{segment}_end", high, "segment_edge"))
        rows.append(Endpoint(f"seg{segment}_end+1", high + 1, "segment_edge"))

    return unique_endpoints(rows)


def bench_endpoints(max_exp: int) -> list[Endpoint]:
    rows: list[Endpoint] = []

    for n in [2, 3, 5, 10, 100, 1000, 10000, 100000]:
        rows.append(Endpoint(f"small_{n}", n, "small"))

    for exp in range(4, max_exp + 1):
        rows.append(Endpoint(f"2^{exp}", 1 << exp, "power"))

    selected_edges = sorted({4, 10, 19, 20, 24, 28, 32, 34, 36, max_exp})
    for exp in selected_edges:
        if exp > max_exp:
            continue
        base = 1 << exp
        rows.append(Endpoint(f"2^{exp}-1", base - 1, "power_edge"))
        rows.append(Endpoint(f"2^{exp}+1", base + 1, "power_edge"))

    for exp in range(16, max_exp + 1, 6):
        base = 1 << exp
        rows.append(Endpoint(f"3*2^{exp-1}", 3 * (base >> 1), "non_power"))

    return unique_endpoints(rows)


def load_expected(path: Path) -> dict[int, str]:
    if not path.exists():
        return {}

    expected: dict[int, str] = {}
    with path.open(newline="") as handle:
        reader = csv.DictReader(skip_comments(handle), delimiter="\t")
        for row in reader:
            try:
                expected[int(row["end"])] = row["expected_sum"]
            except (KeyError, ValueError):
                continue
    return expected


def skip_comments(handle):
    for line in handle:
        if line.strip() and not line.startswith("#"):
            yield line


def write_expected(path: Path, rows: list[tuple[Endpoint, str, RunResult]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        handle.write("# Generated by prime-suite capture-sums.\n")
        handle.write(f"# generated_at={datetime.now().isoformat(timespec='seconds')}\n")
        writer = csv.DictWriter(
            handle,
            delimiter="\t",
            fieldnames=["label", "end", "kind", "expected_sum", "status", "elapsed_s"],
        )
        writer.writeheader()
        for endpoint, expected_sum, result in rows:
            writer.writerow(
                {
                    "label": endpoint.label,
                    "end": endpoint.end,
                    "kind": endpoint.kind,
                    "expected_sum": expected_sum,
                    "status": "ok" if result.ok else "fail",
                    "elapsed_s": format_seconds(result.elapsed),
                }
            )


def append_run_rows(path: Path, rows: list[dict[str, str]]) -> None:
    if not rows:
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    exists = path.exists() and path.stat().st_size > 0
    fieldnames = list(rows[0].keys())
    with path.open("a", newline="") as handle:
        writer = csv.DictWriter(handle, delimiter="\t", fieldnames=fieldnames)
        if not exists:
            handle.write("# Generated by prime-suite bench/capture-all.\n")
            handle.write(f"# host={platform.node()} platform={platform.platform()}\n")
            writer.writeheader()
        for row in rows:
            writer.writerow(row)


def format_seconds(value: float | None) -> str:
    if value is None or math.isnan(value):
        return "-"
    return f"{value:.6f}"


def resolve_exec(path_text: str) -> Path:
    path = Path(path_text)
    if not path.is_absolute():
        path = (Path.cwd() / path).resolve()
    return path


def maybe_build_executable(exec_path: Path) -> None:
    if exec_path.exists() and os.access(exec_path, os.X_OK):
        return

    parts = exec_path.parts
    if "build" not in parts:
        raise SystemExit(f"Target is not executable: {exec_path}")

    build_index = parts.index("build")
    source_dir = Path(*parts[:build_index])
    target = Path(*parts[build_index:]).as_posix()
    if not (source_dir / "Makefile").exists():
        raise SystemExit(f"Target missing and no Makefile found near it: {exec_path}")

    print(f"Building {exec_path.relative_to(PRIME_DIR)}...", file=sys.stderr)
    subprocess.run(["make", "-C", str(source_dir), target], check=True)

    if not exec_path.exists() or not os.access(exec_path, os.X_OK):
        raise SystemExit(f"Build did not produce executable target: {exec_path}")


def run_program(exec_path: Path, endpoint: int, timeout: float | None) -> RunResult:
    start = time.perf_counter()
    try:
        completed = subprocess.run(
            [str(exec_path), str(endpoint), "--sum-only"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return RunResult(False, time.perf_counter() - start, "", 124, "timeout")
    except OSError as exc:
        return RunResult(False, time.perf_counter() - start, "", 127, str(exc))

    elapsed = time.perf_counter() - start
    stdout = completed.stdout.strip()
    stderr = completed.stderr.strip()
    return RunResult(completed.returncode == 0, elapsed, stdout, completed.returncode, stderr)


def run_true_once(true_path: Path) -> float:
    start = time.perf_counter()
    subprocess.run([str(true_path)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
    return time.perf_counter() - start


def measure_latency(true_path: Path, samples: int, sleep_s: float) -> TimingStats:
    times: list[float] = []
    for index in range(samples):
        times.append(run_true_once(true_path))
        if index + 1 < samples:
            time.sleep(sleep_s)
    return stats_from_times(times)


def stats_from_times(times: list[float]) -> TimingStats:
    if not times:
        return TimingStats(0, math.nan, math.nan, math.nan, math.nan, 0.0)

    return TimingStats(
        repeats=len(times),
        best=min(times),
        median=statistics.median(times),
        mean=statistics.mean(times),
        stdev=statistics.stdev(times) if len(times) > 1 else 0.0,
        total=sum(times),
    )


def choose_target_repeats(first_elapsed: float, args: argparse.Namespace) -> int:
    if first_elapsed < args.low_threshold:
        return args.max_repeats
    if first_elapsed >= args.slow_single_threshold:
        return 1
    if first_elapsed >= args.slow_three_threshold:
        return min(3, args.runs)
    return args.runs


def measure_endpoint(
    exec_path: Path,
    endpoint: Endpoint,
    args: argparse.Namespace,
    remaining_budget: float | None,
) -> tuple[TimingStats, str, RunResult, bool]:
    times: list[float] = []
    sums: list[str] = []
    timeout = remaining_budget if remaining_budget is not None else args.per_run_timeout

    if args.warmups > 0:
        for _ in range(args.warmups):
            warmup = run_program(exec_path, endpoint.end, timeout)
            if not warmup.ok:
                return stats_from_times(times), warmup.stdout, warmup, False

    first = run_program(exec_path, endpoint.end, timeout)
    if not first.ok:
        return stats_from_times(times), first.stdout, first, False

    times.append(first.elapsed)
    sums.append(first.stdout)

    target_repeats = choose_target_repeats(first.elapsed, args)
    while len(times) < target_repeats:
        if sum(times) >= args.min_sample_seconds and first.elapsed < args.low_threshold:
            break

        if remaining_budget is not None and sum(times) >= remaining_budget:
            break

        timeout = None
        if remaining_budget is not None:
            timeout = max(0.001, remaining_budget - sum(times))
        elif args.per_run_timeout is not None:
            timeout = args.per_run_timeout

        result = run_program(exec_path, endpoint.end, timeout)
        if not result.ok:
            return stats_from_times(times), result.stdout, result, False
        times.append(result.elapsed)
        sums.append(result.stdout)

    same_sum = all(value == sums[0] for value in sums)
    return stats_from_times(times), sums[0], first, same_sum


def endpoint_suite(name: str, max_exp: int) -> list[Endpoint]:
    if name == "standard":
        return standard_endpoints(max_exp)
    if name == "bench":
        return bench_endpoints(max_exp)
    raise SystemExit(f"Unknown endpoint suite: {name}")


def compare_sum(actual: str, expected: str | None) -> str:
    if expected is None:
        return "unknown"
    return "yes" if actual == expected else "MISMATCH"


def command_latency(args: argparse.Namespace) -> int:
    true_path = Path(args.true_path)
    stats = measure_latency(true_path, args.latency_samples, args.latency_sleep)
    print(f"Harness latency using {true_path}:")
    print(f"  samples: {stats.repeats}")
    print(f"  sleep between samples: {args.latency_sleep:.2f}s")
    print(f"  best:   {format_seconds(stats.best)}s")
    print(f"  median: {format_seconds(stats.median)}s")
    print(f"  mean:   {format_seconds(stats.mean)}s")
    print(f"  stdev:  {format_seconds(stats.stdev)}s")
    return 0


def run_suite(args: argparse.Namespace, mode: str) -> int:
    exec_path = resolve_exec(args.executable)
    maybe_build_executable(exec_path)

    expected = load_expected(Path(args.expected))
    endpoints = endpoint_suite(args.endpoint_suite, args.max_exp)
    started = time.perf_counter()
    mismatches = 0
    failures = 0
    run_rows: list[dict[str, str]] = []

    print()
    print(f"Target: {relative_display(exec_path)}")
    print(f"Mode: {mode}")
    print(f"Endpoint suite: {args.endpoint_suite}, max_exp={args.max_exp}, cases={len(endpoints)}")
    if expected:
        print(f"Expected sums: {relative_display(Path(args.expected))}")
    else:
        print(f"Expected sums: missing ({relative_display(Path(args.expected))}); correctness is unknown")

    latency_stats = None
    if args.latency_samples > 0:
        print()
        print("Measuring harness latency...")
        latency_stats = measure_latency(Path(args.true_path), args.latency_samples, args.latency_sleep)
        print(
            "Latency /usr/bin/true: "
            f"median={format_seconds(latency_stats.median)}s "
            f"best={format_seconds(latency_stats.best)}s "
            f"samples={latency_stats.repeats}"
        )

    print()
    print(
        f"{'label':<18} {'end':>14} {'reps':>5} {'best_s':>10} {'median_s':>10} "
        f"{'mean_s':>10} {'sum_ok':>8} {'notes'}"
    )
    print("-" * 90)

    for endpoint in endpoints:
        remaining = None
        if args.time_budget is not None:
            remaining = args.time_budget - (time.perf_counter() - started)
            if remaining <= 0:
                print(f"Budget exhausted before {endpoint.label}; stopping.")
                break

        stats, actual_sum, first, same_sum = measure_endpoint(exec_path, endpoint, args, remaining)
        expected_sum = expected.get(endpoint.end)
        sum_ok = compare_sum(actual_sum, expected_sum)
        notes: list[str] = []

        if not first.ok:
            failures += 1
            notes.append(first.error or f"exit {first.returncode}")
        if not same_sum:
            failures += 1
            notes.append("unstable sum")
        if sum_ok == "MISMATCH":
            mismatches += 1
            notes.append(f"expected {expected_sum}")

        print(
            f"{endpoint.label:<18} {endpoint.end:>14} {stats.repeats:>5} "
            f"{format_seconds(stats.best):>10} {format_seconds(stats.median):>10} "
            f"{format_seconds(stats.mean):>10} {sum_ok:>8} {'; '.join(notes)}"
        )

        if args.out is not None:
            run_rows.append(
                make_run_row(
                    args=args,
                    mode=mode,
                    exec_path=exec_path,
                    endpoint=endpoint,
                    stats=stats,
                    actual_sum=actual_sum,
                    sum_ok=sum_ok,
                    latency_stats=latency_stats,
                    status="ok" if first.ok and same_sum else "fail",
                    notes="; ".join(notes),
                )
            )

        if args.stop_on_failure and (mismatches or failures):
            break

    if args.out is not None:
        append_run_rows(Path(args.out), run_rows)
        print()
        print(f"Wrote {len(run_rows)} rows to {relative_display(Path(args.out))}")

    print()
    print(f"Finished in {format_seconds(time.perf_counter() - started)}s.")
    if mismatches or failures:
        print(f"Problems: {mismatches} sum mismatch(es), {failures} failure(s).")
        return 1
    return 0


def make_run_row(
    args: argparse.Namespace,
    mode: str,
    exec_path: Path,
    endpoint: Endpoint,
    stats: TimingStats,
    actual_sum: str,
    sum_ok: str,
    latency_stats: TimingStats | None,
    status: str,
    notes: str,
) -> dict[str, str]:
    return {
        "captured_at": datetime.now().isoformat(timespec="seconds"),
        "mode": mode,
        "program": exec_path.stem,
        "path": relative_display(exec_path),
        "label": endpoint.label,
        "end": str(endpoint.end),
        "kind": endpoint.kind,
        "repeats": str(stats.repeats),
        "best_s": format_seconds(stats.best),
        "median_s": format_seconds(stats.median),
        "mean_s": format_seconds(stats.mean),
        "stdev_s": format_seconds(stats.stdev),
        "total_sample_s": format_seconds(stats.total),
        "sum": actual_sum,
        "sum_ok": sum_ok,
        "status": status,
        "latency_median_s": format_seconds(latency_stats.median if latency_stats else None),
        "latency_best_s": format_seconds(latency_stats.best if latency_stats else None),
        "host": platform.node(),
        "notes": notes,
    }


def command_capture_sums(args: argparse.Namespace) -> int:
    reference = resolve_exec(args.reference)
    maybe_build_executable(reference)
    endpoints = endpoint_suite(args.endpoint_suite, args.max_exp)
    rows: list[tuple[Endpoint, str, RunResult]] = []
    failures = 0

    print(f"Reference: {relative_display(reference)}")
    print(f"Capturing {len(endpoints)} expected sums to {relative_display(Path(args.out))}")

    for endpoint in endpoints:
        result = run_program(reference, endpoint.end, args.per_run_timeout)
        expected_sum = result.stdout if result.ok else "-"
        rows.append((endpoint, expected_sum, result))
        status = "ok" if result.ok else "FAIL"
        if not result.ok:
            failures += 1
        print(f"{endpoint.label:<18} {endpoint.end:>14} {status:>5} {format_seconds(result.elapsed):>10}s")

    write_expected(Path(args.out), rows)
    print(f"Wrote {relative_display(Path(args.out))}")
    return 1 if failures else 0


def discover_executables() -> list[Path]:
    results: list[Path] = []
    for subdir_name in ["mine", "ai"]:
        subdir = PRIME_DIR / subdir_name
        if not subdir.exists():
            continue
        for source in sorted(subdir.glob("*.c")):
            results.append(subdir / "build" / f"{source.stem}.exe")
    return results


def command_capture_all(args: argparse.Namespace) -> int:
    executables = discover_executables()
    if args.only:
        wanted = set(args.only)
        executables = [path for path in executables if path.stem in wanted or path.name in wanted]

    if not executables:
        print("No programs discovered.")
        return 1

    print("Discovered programs:")
    for path in executables:
        print(f"  {relative_display(path)}")

    failures = 0
    for exec_path in executables:
        print()
        print(f"=== {relative_display(exec_path)} ===")
        child_args = argparse.Namespace(**vars(args))
        child_args.executable = str(exec_path)
        child_args.out = args.out
        failures += 1 if run_suite(child_args, "bench") else 0
    return 1 if failures else 0


def relative_display(path: Path) -> str:
    path = path.resolve()
    try:
        return str(path.relative_to(PRIME_DIR))
    except ValueError:
        return str(path)


def add_common_timing_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--runs", type=parse_nonnegative_int, default=5)
    parser.add_argument("--warmups", type=parse_nonnegative_int, default=1)
    parser.add_argument("--min-sample-seconds", type=parse_positive_float, default=1.0)
    parser.add_argument("--max-repeats", type=parse_nonnegative_int, default=200)
    parser.add_argument("--low-threshold", type=parse_positive_float, default=0.050)
    parser.add_argument("--slow-three-threshold", type=parse_positive_float, default=2.0)
    parser.add_argument("--slow-single-threshold", type=parse_positive_float, default=10.0)
    parser.add_argument("--per-run-timeout", type=parse_positive_float, default=None)


def add_latency_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--true-path", default="/usr/bin/true")
    parser.add_argument("--latency-samples", type=parse_nonnegative_int, default=7)
    parser.add_argument("--latency-sleep", type=float, default=1.0)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="PrimeSum test and benchmark suite")
    subparsers = parser.add_subparsers(dest="command", required=True)

    test_parser = subparsers.add_parser("test", help="quick correctness and timing sanity check")
    test_parser.add_argument("executable")
    test_parser.add_argument("--max-exp", type=parse_nonnegative_int, default=34)
    test_parser.add_argument("--endpoint-suite", choices=["standard", "bench"], default="standard")
    test_parser.add_argument("--expected", default=str(DEFAULT_EXPECTED))
    test_parser.add_argument("--out", default=None)
    test_parser.add_argument("--time-budget", type=parse_positive_float, default=None)
    test_parser.add_argument("--stop-on-failure", action="store_true")
    add_common_timing_args(test_parser)
    add_latency_args(test_parser)
    test_parser.set_defaults(func=lambda args: run_suite(args, "test"))

    bench_parser = subparsers.add_parser("bench", help="comparison benchmark up to budget or max exponent")
    bench_parser.add_argument("executable")
    bench_parser.add_argument("--max-exp", type=parse_nonnegative_int, default=40)
    bench_parser.add_argument("--endpoint-suite", choices=["standard", "bench"], default="bench")
    bench_parser.add_argument("--expected", default=str(DEFAULT_EXPECTED))
    bench_parser.add_argument("--out", default=str(DEFAULT_RUNS))
    bench_parser.add_argument("--time-budget", type=parse_positive_float, default=7200.0)
    bench_parser.add_argument("--stop-on-failure", action="store_true")
    add_common_timing_args(bench_parser)
    add_latency_args(bench_parser)
    bench_parser.set_defaults(func=lambda args: run_suite(args, "bench"))

    capture_sums_parser = subparsers.add_parser("capture-sums", help="capture expected sums from reference")
    capture_sums_parser.add_argument("reference")
    capture_sums_parser.add_argument("--max-exp", type=parse_nonnegative_int, default=40)
    capture_sums_parser.add_argument("--endpoint-suite", choices=["standard", "bench"], default="standard")
    capture_sums_parser.add_argument("--out", default=str(DEFAULT_EXPECTED))
    capture_sums_parser.add_argument("--per-run-timeout", type=parse_positive_float, default=None)
    capture_sums_parser.set_defaults(func=command_capture_sums)

    capture_all_parser = subparsers.add_parser("capture-all", help="benchmark all discovered programs")
    capture_all_parser.add_argument("--max-exp", type=parse_nonnegative_int, default=40)
    capture_all_parser.add_argument("--endpoint-suite", choices=["standard", "bench"], default="bench")
    capture_all_parser.add_argument("--expected", default=str(DEFAULT_EXPECTED))
    capture_all_parser.add_argument("--out", default=str(DEFAULT_RUNS))
    capture_all_parser.add_argument("--time-budget", type=parse_positive_float, default=7200.0)
    capture_all_parser.add_argument("--stop-on-failure", action="store_true")
    capture_all_parser.add_argument("--only", action="append", default=[])
    add_common_timing_args(capture_all_parser)
    add_latency_args(capture_all_parser)
    capture_all_parser.set_defaults(func=command_capture_all)

    latency_parser = subparsers.add_parser("latency", help="measure subprocess harness latency")
    add_latency_args(latency_parser)
    latency_parser.set_defaults(func=command_latency)

    list_parser = subparsers.add_parser("list-endpoints", help="print generated endpoint set")
    list_parser.add_argument("--max-exp", type=parse_nonnegative_int, default=34)
    list_parser.add_argument("--endpoint-suite", choices=["standard", "bench"], default="standard")
    list_parser.set_defaults(func=command_list_endpoints)

    return parser


def command_list_endpoints(args: argparse.Namespace) -> int:
    for endpoint in endpoint_suite(args.endpoint_suite, args.max_exp):
        print(f"{endpoint.label}\t{endpoint.end}\t{endpoint.kind}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if shutil.which("make") is None:
        print("Warning: make not found; automatic builds may fail.", file=sys.stderr)

    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
